#!/usr/bin/env python3
"""Lints the backlog, reads the milestones out of their tests, and renders the roadmap.

    scripts/backlog.py lint     validate docs/backlog.md
    scripts/backlog.py render   rewrite docs/roadmap.md
    scripts/backlog.py check    lint, then fail if docs/roadmap.md is not what render would write

The milestone table is built from `tests/milestones/M*.sh` rather than from a hand-kept list,
because the tests are what actually decide whether a milestone is met. A table typed by hand drifts
the first time someone is in a hurry, and then the document quietly describes a repository that no
longer exists.

Standard library only: this runs in CI as a gate, and a gate that needs installing is a gate that
gets skipped.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKLOG = ROOT / "docs" / "backlog.md"
ROADMAP = ROOT / "docs" / "roadmap.md"
MILESTONES = ROOT / "tests" / "milestones"

PRIORITIES = ("high", "medium", "low")
STATUSES = ("open", "doing", "done", "dropped")

ITEM_RE = re.compile(r"^## (BL-\d{2}) — (.+)$", re.M)
META_RE = re.compile(
    r"\*\*Priority:\*\* (\w+) · \*\*Status:\*\* (\w+) · \*\*Milestone:\*\* (\S+)"
)
DONE_RE = re.compile(r"^\*\*Done when:\*\* (.+)$", re.M | re.S)


def read_backlog():
    text = BACKLOG.read_text()
    items, errors = [], []
    matches = list(ITEM_RE.finditer(text))
    for i, m in enumerate(matches):
        body = text[m.end(): matches[i + 1].start() if i + 1 < len(matches) else len(text)]
        item = {"id": m.group(1), "title": m.group(2).strip()}
        meta = META_RE.search(body)
        if not meta:
            errors.append(f"{item['id']}: no metadata line (Priority / Status / Milestone)")
            continue
        item["priority"], item["status"], item["milestone"] = meta.groups()
        if item["priority"] not in PRIORITIES:
            errors.append(f"{item['id']}: priority '{item['priority']}' is not one of {PRIORITIES}")
        if item["status"] not in STATUSES:
            errors.append(f"{item['id']}: status '{item['status']}' is not one of {STATUSES}")
        if not DONE_RE.search(body):
            # Without it an item is a complaint, not a task: nobody can tell when to stop.
            errors.append(f"{item['id']}: no '**Done when:**' line")
        items.append(item)

    seen = {}
    for item in items:
        if item["id"] in seen:
            errors.append(f"{item['id']}: duplicate id")
        seen[item["id"]] = item
    if not items:
        errors.append("the backlog is empty — or its format changed and nothing parses any more")
    return items, errors


def read_milestones():
    """Milestone id, title and whether it is declared reached, taken from the test files."""
    out = []
    for path in sorted(MILESTONES.glob("M*.sh")):
        text = path.read_text()
        m = re.search(r'^milestone (\S+) "([^"]+)"', text, re.M)
        if not m:
            continue
        expect = re.search(r"^expect (\w+)", text, re.M)
        scope = []
        for op, n in re.findall(r"^only_major (\w+) (\d+)", text, re.M):
            scope.append(f"Kong {'>=' if op == 'ge' else '<'} {n}")
        for provider in re.findall(r"^only_provider (\S+)", text, re.M):
            scope.append(f"{provider} image")
        out.append({
            "id": m.group(1),
            "title": m.group(2),
            "reached": (expect.group(1) if expect else "pass") == "pass",
            "scope": ", ".join(scope) or "every image",
            "test": path.name,
        })
    return out


def slug(item_id, title):
    """The anchor MkDocs will produce for `## BL-01 — Title`.

    Reimplemented rather than guessed: the `markdown` toc extension strips everything that is not a
    word character, whitespace or a hyphen — the em dash goes, the backticks go — then lowercases
    and collapses runs of spaces and hyphens into one. Generating a link that looks right and
    resolves to nothing is worse than no link, because nobody checks the ones that look right.
    """
    text = f"{item_id} — {title}"
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[-\s]+", "-", text)


def render():
    items, _ = read_backlog()
    milestones = read_milestones()
    open_items = [i for i in items if i["status"] in ("open", "doing")]
    by_priority = {p: [i for i in open_items if i["priority"] == p] for p in PRIORITIES}

    lines = [
        "# Roadmap",
        "",
        "<!-- Generated by scripts/backlog.py from tests/milestones/ and docs/backlog.md."
        " Do not edit: CI regenerates it and fails if this file is stale. -->",
        "",
        "Milestone state comes from the tests themselves, not from a list kept by hand — the tests"
        " are what decide whether a milestone is met, so anything else is a copy waiting to drift.",
        "",
        "## Milestones",
        "",
        "| | Milestone | Applies to | State |",
        "|---|---|---|---|",
    ]
    for ms in milestones:
        state = "🟢 reached" if ms["reached"] else "🟡 declared outstanding (`XFAIL`)"
        lines.append(f"| **{ms['id']}** | {ms['title']} | {ms['scope']} | {state} |")

    lines += ["", "## Open work", ""]
    if not open_items:
        lines.append("_Nothing open._")
    for priority in PRIORITIES:
        chosen = by_priority[priority]
        if not chosen:
            continue
        lines += [f"### {priority.capitalize()}", "", "| | Item | Unblocks |", "|---|---|---|"]
        for item in chosen:
            unblocks = item["milestone"] if item["milestone"] != "-" else "—"
            link = f"[{item['title']}](backlog.md#{slug(item['id'], item['title'])})"
            lines += [f"| `{item['id']}` | {link} | {unblocks} |"]
        lines.append("")

    done = [i for i in items if i["status"] == "done"]
    if done:
        lines += ["## Finished", ""] + [f"- `{i['id']}` {i['title']}" for i in done] + [""]

    lines += [
        "---",
        "",
        f"{len(open_items)} open, {len(done)} finished, "
        f"{sum(1 for m in milestones if m['reached'])} of {len(milestones)} milestones reached.",
        "",
    ]
    return "\n".join(lines)


def main():
    action = sys.argv[1] if len(sys.argv) > 1 else "check"
    items, errors = read_backlog()
    if errors:
        for e in errors:
            print(f"  FAIL {e}")
        print(f"RED: {len(errors)} backlog problem(s)")
        return 1
    print(f"  ok   {len(items)} backlog items parse, with priority, status and a done-when")

    if action == "lint":
        return 0

    rendered = render()
    if action == "render":
        ROADMAP.write_text(rendered)
        print(f"  ok   wrote {ROADMAP.relative_to(ROOT)}")
        return 0

    if action == "check":
        current = ROADMAP.read_text() if ROADMAP.exists() else ""
        if current != rendered:
            print("  FAIL docs/roadmap.md is stale — run: python3 scripts/backlog.py render")
            return 1
        print("  ok   docs/roadmap.md matches the backlog and the milestone tests")
        return 0

    print(f"unknown action '{action}' (lint, render, check)")
    return 2


if __name__ == "__main__":
    sys.exit(main())
